### ISSUE TITLE
Incorrect rows/columns comment

### ISSUE THREAD

**Issue by cdilga** [agyorev/Eigenfaces#4]
https://github.com/agyorev/Eigenfaces/blob/202e8f517f89722199a55d5e36597dc75d0b61b0/eigenfaces.py#L102

As per the np.linalg.eig docs, the vectors are column wise, not row wise
https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.linalg.eig.html

**Comment by zhji2822** [comment]
I think the line need to be deleted and the code can be run

**Comment by clhne** [comment]
> I think the line need to be deleted and the code can be run

Yes, you're right.

**Comment by agyorev** [comment]
@clhne submitted a fix so now it should work. Thanks everyone!
